server:
  port: 9005

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

spring:
  application:
    name: baidu-config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/myj0918/mmm-kelong.git
          search-paths: /
          username:
          password:
